# -*- coding: utf-8 -*-
"""dataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LOBYTJ8aCFd8hC-b_3-vcIoSmTmui2fH
"""

!apt-get install openjdk-11-jdk-headless -qq > /dev/null
!pip install pyspark

input_path = "/content/drive/MyDrive/Lichess_2013_2014_Complete.csv"

from pyspark.sql import SparkSession
spark = SparkSession.builder \
    .appName("Lichess_TimeControl_Analysis") \
    .getOrCreate()

df = spark.read.option("header", True).csv(input_path)

# muestreo recomendado (1% o 5%) si el dataset completo es pesado
df = df.sample(withReplacement=False, fraction=0.02)
df.count()

df = df.withColumn("TimeControl", F.trim(F.col("TimeControl")))
df.select("TimeControl").distinct().show()

df = df.withColumn("Number_of_Moves", F.col("Number_of_Moves").cast("int"))

df = df.withColumn("white_win", F.when(F.col("Winner")=="White", 1).otherwise(0))
df = df.withColumn("black_win", F.when(F.col("Winner")=="Black", 1).otherwise(0))
df = df.withColumn("draw",      F.when(F.col("Winner")=="Draw", 1).otherwise(0))

stats = df.groupBy("TimeControl").agg(
    F.count("*").alias("games"),
    F.mean("Number_of_Moves").alias("avg_moves"),
    F.mean("white_win").alias("prop_white_win"),
    F.mean("black_win").alias("prop_black_win"),
    F.mean("draw").alias("prop_draw")
)

stats.show(truncate=False)

import pandas as pd

pdf = stats.toPandas()
pdf

import matplotlib.pyplot as plt

plt.figure(figsize=(8,4))
plt.bar(pdf["TimeControl"], pdf["avg_moves"])
plt.title("Promedio de movimientos por tipo de partida")
plt.xlabel("TimeControl")
plt.ylabel("Movimientos")
plt.show()

plt.figure(figsize=(8,4))
plt.bar(pdf["TimeControl"], pdf["prop_white_win"])
plt.title("Proporción de victorias blancas")
plt.show()

plt.figure(figsize=(8,4))
plt.bar(pdf["TimeControl"], pdf["prop_black_win"])
plt.title("Proporción de victorias negras")
plt.show()

plt.figure(figsize=(8,4))
plt.bar(pdf["TimeControl"], pdf["prop_draw"])
plt.title("Proporción de tablas")
plt.show()